/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */

export * from './analyzeResult';
export * from './error';
export * from './widget';
export * from './widgetColor';
export * from './widgetList';
export * from './widgetMergePatchUpdate';
export * from './widgetMergePatchUpdateColor';