/**
 * Generated by orval v8.0.0 🍺
 * Do not edit manually.
 * Widget Service
 * OpenAPI spec version: 0.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AnalyzeResult,
  Widget,
  WidgetList,
  WidgetMergePatchUpdate
} from './model';




  export const getWidgetService = () => {
/**
 * List widgets
 */
const widgetsList = <TData = AxiosResponse<WidgetList>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/v2/widgets`,options
    );
  }

/**
 * Create a widget
 */
const widgetsCreate = <TData = AxiosResponse<Widget>>(
    widget: Widget, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/v2/widgets`,
      widget,options
    );
  }

/**
 * Read widgets
 */
const widgetsRead = <TData = AxiosResponse<Widget>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/v2/widgets/${id}`,options
    );
  }

/**
 * Update a widget
 */
const widgetsUpdate = <TData = AxiosResponse<Widget>>(
    id: string,
    widgetMergePatchUpdate: WidgetMergePatchUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/api/v2/widgets/${id}`,
      widgetMergePatchUpdate,options
    );
  }

/**
 * Delete a widget
 */
const widgetsDelete = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/v2/widgets/${id}`,options
    );
  }

/**
 * Analyze a widget
 */
const widgetsAnalyze = <TData = AxiosResponse<AnalyzeResult>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/v2/widgets/${id}/analyze`,undefined,options
    );
  }

return {widgetsList,widgetsCreate,widgetsRead,widgetsUpdate,widgetsDelete,widgetsAnalyze}};
export type WidgetsListResult = AxiosResponse<WidgetList>
export type WidgetsCreateResult = AxiosResponse<Widget>
export type WidgetsReadResult = AxiosResponse<Widget>
export type WidgetsUpdateResult = AxiosResponse<Widget>
export type WidgetsDeleteResult = AxiosResponse<void>
export type WidgetsAnalyzeResult = AxiosResponse<AnalyzeResult>
